name: Docker Publish

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - closed

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[Build]') || github.event.pull_request.merged == true }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aethrexal/metra:latest
